# -*- coding: utf-8 -*-
"""scrapedcsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pk5IXGOBBIKYv6kWuqDCEUsVWM5FCyaa
"""

import pandas as pd

# Simulate scraped data (since we cannot run actual web scraping here)
data = [
    {
        "NEWS_TITLE": "India celebrates Republic Day with grandeur",
        "NEWS_LINK": "https://indianexpress.com/article/india/india-republic-day-celebration-9145878/",
        "FULL_SCRAPED_TEXT": "India marked its 76th Republic Day with a grand parade showcasing its cultural diversity and military prowess..."
    },
    {
        "NEWS_TITLE": "Budget 2025 highlights: Key takeaways",
        "NEWS_LINK": "https://indianexpress.com/article/business/budget-2025-key-highlights-9145991/",
        "FULL_SCRAPED_TEXT": "Finance Minister presented the Budget 2025 focusing on infrastructure, digital economy, and green energy..."
    },
    {
        "NEWS_TITLE": "Supreme Court rules on environmental regulations",
        "NEWS_LINK": "https://indianexpress.com/article/india/supreme-court-environment-ruling-9146012/",
        "FULL_SCRAPED_TEXT": "The Supreme Court of India passed a landmark judgment reinforcing environmental protection laws..."
    }
]

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV with required column names
csv_path = "indian_express_scraped_articles.csv"
df.to_csv(csv_path, index=False)

csv_path